---
title: "Linguistic data: quantitative analysis and visualisation"
---

### R and RStudio installation
[R](https://www.r-project.org/), [RStudio](https://www.rstudio.com/products/rstudio/download/#download), [RStudio online](https://www.rollapp.com/app/rstudio) ------- [Connecting RStudio and GitHub](http://happygitwithr.com/rstudio-git-github.html), [R-bloggers](https://www.r-bloggers.com/)

### Course Info	
[Course description](https://agricolamz.github.io/2018-MAG_R_course/Lec_1_Course_description.html)
 -- [about Final exam projects](https://agricolamz.github.io/2018-MAG_R_course/projects.html)
 -- [Students & grades](https://docs.google.com/spreadsheets/d/1HdjLzF3jUXddq2N7pUpGn7P1tMJ4ut9mskucVjiNlwQ)   

### 1. Introduction to the course. Introduction to R. Types of data. 
* [Please fill in the form](https://docs.google.com/forms/d/e/1FAIpQLSeHEP4ivqpKUqPJpuruwbbOb_6x05m8ExA_YdiHer7gC3Hzng/viewform?usp=sf_link)  
* (18.01.2018)	[Lab 1](): Basic R objects. Dataframes. Manipulation with data. Simple functions. Base R functions code. User's functions. User's functions. Loops. Functions in functions. Default arguments. Optional arguments.  

* [HW-1. Self-paced online course. Section 1-5 ](https://www.edx.org/course/introduction-r-data-science-microsoft-dat204x-7). Please upload the screenshot of your Course Progess (Quizes 1-11, Labs 1-11) in the folder OnlineCourse in your github repository. Your student name and email are to be seen on the screenshot. Due: next class.

### 2. Descriptive statistics A. Confidence intervals. P-values
* (25.01.2018) [Lec 2: Central limit theorem. Measures of central tendency and dispersion. Confidence intervals]()  
* (25.01.2018) [Lab 2: Simple plots. Read and write data. Manipulation with data (R base vs. dplyr). R markdown.]() 
    * [Test # 1: Basic R techniques (based on online course))[]  
    * RMarkdown [in short](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). [RStudio cheat sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)  
    * [Lab 2 Assignment]()  
* Textbook: Levshina Ch.3-4  

* [HW-2. Self-paced online course. Section 6-7, Final Exam](https://www.edx.org/course/introduction-r-data-science-microsoft-dat204x-7).  Please upload the screenshot of your Course Progess in the folder OnlineCourse in your github repository. Your student name and email are to be seen on the screenshot. Due: next class.

### 3. Data manipulation and visualization.

*	(01.02.2018) [Base R vs. ggplot2: 2 variables, 3 variables, many variables](Lec_3_tidyverse.html)
* [HW-1](https://docs.google.com/forms/d/e/1FAIpQLSc2Z6snhSEZRVzHysYsUdKFkl4flE63AY4TFd-UrkmstV8s4g/viewform). Due: 15.02.2018

### 4. Classical statistical tests: continuos data. T-tests. Mann-Whitney U-test.
* (10.02.2018) [Lec 4](Lec_4_stats.html)
* (10.02.2018) Lab 4: Descriptive statistics, Confidence intervals, T-tests. P-value.
    * [Lab 4 Assignment](https://docs.google.com/forms/d/e/1FAIpQLSdGZSuPIyO7DOcObhkdwlvUFBQPGMm1uM0tXanSY7Loie0A1A/viewform)
    * Files from class: Lab 4
* Textbook: Levshina Ch.5  

* Final Exam Projects: Research topic and hypothesis. Please fill in the form, sheet [Projects](https://docs.google.com/spreadsheets/d/1HdjLzF3jUXddq2N7pUpGn7P1tMJ4ut9mskucVjiNlwQ). Due: 15.02.2018.

### 5. Classical statistical tests: categorial data. Binomial test. Chi-squared test. Fisher exact test. Effect size. Correlations. ANOVA.
* (15.02.2018) [Lab 5 code](https://raw.githubusercontent.com/agricolamz/2018-MAG_R_course/master/Lab5.Rmd)  [Lab 5 solution](https://agricolamz.github.io/2018-MAG_R_course/Lab_5.html).

### 6. Bi-variate regression.															
* (24.02.2018) lecture  
* (24.02.2018) Lab 6: [Assignment](https://docs.google.com/forms/d/e/1FAIpQLSctIDQQBsIGTMjkzuGiAEXVcE9N9EBPrKjkgyuUheVKHewvVQ/viewform), [Code](https://agricolamz.github.io/2018-MAG_R_course/Lab6.html)  
* Textbook: Levshina Ch.6 

### 7. Linear regressions											
* (03.03.2018) lecture  
* (03.03.2018) Lab 7: [Assignment](), [Code]()
* Textbook: Levshina Ch.7 

### 8. Multivariate linear regressions, dummy variables, ANOVA														
* (12.04.2018) Lecture 8
* (12.04.2018) Lab 8: [Assignment](https://raw.githubusercontent.com/agricolamz/2018-MAG_R_course/master/Lab8_assignment.Rmd), [Code](https://agricolamz.github.io/2018-MAG_R_course/Lab6.html)
* Textbook: Levshina Ch.8  

### 9. Linear mixed-effects models. 						
* (26.04.2018) Lecture 9
* (26.04.2018) Lab 9: [Assignment](https://docs.google.com/forms/d/e/1FAIpQLSfQAI87CVsjqbkw1XbvJw_dmj8tET1s-oT9jmQGx9miRRtcMQ/viewform?usp=sf_link), [Code](https://agricolamz.github.io/2018-MAG_R_course/Lab_9)

* [HW-2](https://raw.githubusercontent.com/agricolamz/2018-MAG_R_course/master/HW2_assignment.Rmd). [Html-version](https://agricolamz.github.io/2018-MAG_R_course/HW2) Due: 17.05.2018

### 10. Binary logistic regressions

* (10.05.2018) Lecture 10
* (10.05.2018) Lab 10: Assignment

* HW-4. Due: next class 
* Final Exam Projects: Data. Data annotation. Please put a link here, sheet [Projects](https://docs.google.com/spreadsheets/d/1HdjLzF3jUXddq2N7pUpGn7P1tMJ4ut9mskucVjiNlwQ) Due: 20.05.2018

### 11. Decision trees. Decision forests											
* (.2018) lecture
* (.2018) Lab 11 (CART), Assignment

* HW-5. Due: next class

### 12. Clusterization

* (.2018) lecture
* (.2018) Lab 12: Clusterization. Assignment link

* HW-6. Due: next class

### 13. Principal component analysis, Simple and Multiple correspondence analysis

* (.2018) Lecture 13
* (.2018) Lab 13: PCA, MCA, Assignment link
* (.2018) Lecture 14
* (.2018) Lab 14: PCA, MCA, Assignment link

### 14. Empirical Bayes

* (.2018) lecture
* (.2018) Lab 14, Assignment link

### 15. Statistics for Hackers

* (.2018) lecture
* (.2018) Lab 15, Assignment link

### Project presentation schedule

### Textbooks

* Levshina, Natalia. 2015. How to do Linguistics with R. [Info](https://benjamins.com/#catalog/books/z.195/main) [Companion web site](https://benjamins.com/sites/z.195/). The e-book is available in HSE library. 
* Gries, Stefan Th. 2013. Statistics for Linguistics with R: A Practical Introduction. 2nd ed. Mouton de Gruyter. [Info](https://www.degruyter.com/view/product/203826) 
* Gries, Stefan Th. 2009 (2nd ed.: 2018). Quantitative Corpus Linguistics with R. Routledge. [Info](https://www.routledge.com/Quantitative-Corpus-Linguistics-with-R-A-Practical-Introduction/Gries/p/book/9780415962704) [2nd Edition](https://www.routledge.com/Quantitative-Corpus-Linguistics-with-R-A-Practical-Introduction-2nd-Edition/Gries/p/book/9781138816275) [Companion page](http://www.linguistics.ucsb.edu/faculty/stgries/research/qclwr/qclwr.html) 
* Baayen, Harald. 2008 (2nd ed.: 2014). Analyzing Linguistic Data: A Practical Introduction to Statistics using R. Cambridge University Press. [Info](http://www.cambridge.org/gb/academic/subjects/languages-linguistics/grammar-and-syntax/analyzing-linguistic-data-practical-introduction-statistics-using-r?format=AR) [Google books](https://books.google.ru/books?id=UvWkIg5E4foC&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false) 

see also our [Course Program](https://www.hse.ru/data/2016/09/19/1117082144/program-1549532002-kSLnTng0SN.pdf)

### R Markdown

* [R Markdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)
* [Online Introduction to R Markdown](http://rmarkdown.rstudio.com/lesson-1.html)
