---
title: "Lab 12. Claster analysis"
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

### [Assignment link](https://goo.gl/uFsyfd)

```{r}
library(tidyverse)
```

### 1.
```{r}
df <- read.csv("https://raw.githubusercontent.com/agricolamz/2018-MAG_R_course/master/data/baltic.csv")
d <- dist(t(df[,3:6]))
set.seed(42)
kmeans(d, 3)
hc <- hclust(d)
plot(hc)
```

### 2.
```{r}
df <- read.csv("http://goo.gl/Zjr9aF")
row.names(df) <- df$speaker
d <- dist((df[,-c(6:9, 1)]))
min(d)
set.seed(42)
km <- kmeans(d, 2)
cbind.data.frame(cluster = km$cluster, orientation = df$orientation) %>% 
  count(cluster, orientation)
plot(df[,-c(6:9, 1)], col = km$cluster, pch = c(16, 1)[df$orientation])

df %>% 
  mutate(cluster = km$cluster) %>%
  group_by(cluster) %>% 
  summarise(mean = mean(perceived.as.homo.percent),
            sd = sd(perceived.as.homo.percent))

hc <- hclust(d)
plot(hc)

p <- pvclust::pvclust(t(df[,-c(1, 9, 10)]),
                      method.dist="cor",
                      method.hclust="average", 
                      nboot=100)
plot(p)
```

## 3
```{r}
library(ape)
df <- read.csv("https://goo.gl/4sJqv1")
data <- df[,-c(1:3)]
row.names(data) <- paste(1:294, df$english)

data %>% 
  dist() %>% 
  hclust() ->
  hc

plot(as.phylo(hc), 
     type = "fan",
     cex = 0.6,
     no.margin = TRUE,
     tip.color = c("red",
                   "blue",
                   "green",
                   "black",
                   "yellow",
                   "pink", 
                   "navy")[df$cognate_set])
```

