---
title: "Decision Trees and Forests"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### [Assignment link](https://goo.gl/FsdBEF)

```{r, message=FALSE}
library(party)
```

### 1.
```{r}
df <- read.csv("http://goo.gl/aE3yVg")
fit <- ctree(v.elision~., data = df)
plot(fit)
print(fit)
predict(fit, df[45,-1], response = TRUE)
fit2 <- cforest(v.elision~., data = df, controls=cforest_unbiased(ntree=1000, mtry=2))
predict(fit2, df[45,-1],OOB=TRUE)
varimp(fit2)
```


### 2.
```{r}
df <- read.csv("https://goo.gl/F9m4O2")
fit <- ctree(s.deletion~phon.cont+social, data = df)
plot(fit)
print(fit)
predict(fit, df[1,-c(1:2)], response = TRUE)
fit2 <- cforest(s.deletion~phon.cont+social, data = df, controls=cforest_unbiased(ntree=100, mtry=2))
varimp(fit2)
```

### 3.
```{r}
shva <- read.csv("https://raw.githubusercontent.com/agricolamz/2018-MAG_R_course/master/data/duryagin_ReductionRussian.txt", sep = "\t")
fit <- ctree(vowel~f1+f2, data = shva)
plot(fit)
print(fit)
predict(fit, newdata = data.frame(f1 = as.integer(600),
                        f2 = as.integer(1300)), response = TRUE)
fit2 <- cforest(vowel~f1+f2, data = shva, controls=cforest_unbiased(ntree=100, mtry=2))
varimp(fit2)
predict(fit2, newdata = data.frame(f1 = as.integer(600),
                        f2 = as.integer(1300)),OOB=TRUE)


fit
```

