---
title: "Examples of research papers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale("LC_ALL", 'en_US.UTF-8')
```

NB The following lists contains documents, scripts and data of different quality.    
For orientation only, not to be cited and distributed.      

## Bachelor and master papers, HSE, 2014--2017  

## In English  
* Daria Shershneva, Varvara Gutz. Pronunciation of the word 'chto' in Russian dialects. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/guts_shershneva_cho.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/guts_shershneva_cho.Rmd)      
* Natalia Akutina. Russian multiverb constructions. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Akutina_Russian_serial_constructions.pdf) [R code](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Akutina_Russian_serial_constructions.R)   
* Vasilisa Zhigulskaya. Initial [n] in the third person pronouns in prepositional constructions in the dialect of Mikhalevskaya village. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Zhigulskaya_pronouns.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Zhigulskaya_pronouns.Rmd)    
* Elizaveta Kuzmenko. Attributive participial clauses in English and learner English. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Kuzmenko_DA_project.pdf) [ipynb](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Kuzmenko_DA_project.ipynb)    
* Ilya Chechuro, Polina Kasyanova. Rival forms in UDI. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Chechuro_Kasyanova_Udi_AOP.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Chechuro_Kasyanova_Udi_AOP.Rmd)    
* Evgeniya Murzinova, Maria Yaroslavtseva. Expressing Plurality in West Circassian. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Murzinova_Yaroslavtseva_txe.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Murzinova_Yaroslavtseva_txe.Rmd)    
* Daria Lapenkova, Alexey Shelepov. Usage of the verbs _mignut'_ / _podmignut'_ in Russian. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Lapenkova_Shelepov.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Lapenkova_Shelepov.Rmd)    
* Denis Arsentyev. The variability of number in Latin borrowings in the English language. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Arsentyev_Denis_The-variability-of-the-verb-number.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Arsentyev_Denis_The-variability-of-the-verb-number.Rmd)    
* George Moiseev, Alexander Nasedkin. Social Network writing style analysis. [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/moiseev_g_final-project.Rmd)    
* Kirill Milinzevich, Ivan Rodin. Barbarisms in the Russian web-discourse. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Milintsevich_Barbarisms.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Milintsevich_Barbarisms.Rmd)    
* Aygul' Zakirova. The debitive nominalization in Moksha: a case of differential object marking. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Zakirova_moksh_debitive.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Zakirova_moksh_debitive.Rmd)    
* Anastasia Lopukhina. Generic-nongeneric utterances interpretation in healthy population and in population with aphasia. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/.Rmd)     

## In Russian
* Соня Никифорова, Яна Курмачева. Распределение предлогов ПРО и О/ОБ в речи. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Nikiforova_Kurmacheva_Prepositions.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Nikiforova_Kurmacheva_Prepositions.Rmd)    
* Ангелина Присяжная. Тенденции выбора падежной формы в конструкциях типа “Фермер продал три овцы / трех овец”. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Prisyazhnaya_tri_ovtsy.pdf)     
* Вероника Данилова, Мария Пономарева. Партитивное использование формы генитива с местоимениями. [paper](https://github.com/agricolamz/2018-MAG_R_course/blob/master/projects_examples/Danilova_Ponomareva_chto-to_Gen.pdf) [Rmd](https://agricolamz.github.io/2018-MAG_R_course/projects_examples/Danilova_Ponomareva_chto-to_Gen.Rmd)     

## Datasets for some case studies  

* Галина Абдурашитова. Двойное отрицание в английском.	[data](https://drive.google.com/drive/folders/0B_wha02nRkzkQUZsZXVhV1NIeVE)  
* Василиса Андриянец. Конструкции, описывающие передвижение на транспорте в русском языке (_на поезде_/_поездом_/_в поезде_). [data](https://drive.google.com/drive/folders/0B21wcBDQwYJbekpfRGVSM1JHOUk?usp=sharing)   
* Анна Кузнецова. Конструкции “the type to”, “the sort to”, “the kind to”: сравнение по семантике, синтаксису и употреблению.	[data](https://drive.google.com/drive/folders/0B1jo4wnZ3s7uOWg5ck5rNk9wVFk)   
* Лена Шакурова. Изучение конструкций с предлогами места в русском и немецком языках. [data](https://docs.google.com/spreadsheets/d/1ZSQzDZirzGuxE0i1z_9vlm8nLqmRmGchyTyRdJpl4go/edit?usp=sharing)  
* Маша Шеянова. Конструкция X do Y в польском: семантика и конкуренты. [data](https://drive.google.com/drive/u/0/folders/0B82eKZSAQ0dbXzI2TjJCdk5FWVk)  
* Ксения Сухова. Описание конструкции “Уж Х то …”	[data](https://docs.google.com/spreadsheets/d/1W08hG6Jm0q5UwKkwQldwY4ywebSoqIDX8M-u8YP__yM/edit?usp=sharing)  
* Ковалевская Владислава Употребление наречных выражений с “по”, образованных от глаголов (_по приезду_, _по приходу_, _по отправлении_ и др.).	[data](https://docs.google.com/spreadsheets/d/1wSiwc80LCiB_6JeEJboypYEsUtALYL0Wzi7n7OU1VI4/edit#gid=0)  
* Игнатьев Григорий Александрович Анализ конструкций “(не) мочь/уметь в Х-а” (“я не умею в начерталку”) на материале твиттера.	[data](https://github.com/gree-gorey/constructions)  